In [41]:
import os
import sys

import pandas as pd
import numpy as np
np.random.seed(1337)  # for reproducibility

from sklearn import svm
from sklearn.externals import joblib
from sklearn.cross_validation import train_test_split
from sklearn.model_selection import GridSearchCV

import sklearn.metrics
from scipy.misc import imread, imsave
from sklearn.externals import joblib


import h2o

In [2]:
dfTrain = pd.read_csv('Train.csv')
print dfTrain.shape
print dfTrain.columns

(6414012, 5)
Index([u'Unnamed: 0', u'Red', u'Green', u'Blue', u'Mask'], dtype='object')


In [3]:
dfTrain = dfTrain.drop('Unnamed: 0', 1)

In [5]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
; Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)
  Starting server from D:\Anaconda2\lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: c:\users\aakashg\appdata\local\temp\tmpjsrfo3
  JVM stdout: c:\users\aakashg\appdata\local\temp\tmpjsrfo3\h2o_AakashG_started_from_python.out
  JVM stderr: c:\users\aakashg\appdata\local\temp\tmpjsrfo3\h2o_AakashG_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321... successful.


--------------------------  ------------------------------
H2O cluster uptime:         05 secs
H2O cluster version:        3.10.2.1
H2O cluster version age:    16 days
H2O cluster name:           H2O_from_python_AakashG_6gohan
H2O cluster total nodes:    1
H2O cluster free memory:    3.531 Gb
H2O cluster total cores:    4
H2O cluster allowed cores:  4
H2O cluster status:         accepting new members, healthy
H2O connection url:         http://127.0.0.1:54321
H2O connection proxy:
Python version:             2.7.12 final
--------------------------  ------------------------------

In [6]:
h2o.connect()
train = h2o.H2OFrame(dfTrain)


Connecting to H2O server at http://localhost:54321... successful.


--------------------------  ------------------------------
H2O cluster uptime:         37 secs
H2O cluster version:        3.10.2.1
H2O cluster version age:    16 days
H2O cluster name:           H2O_from_python_AakashG_6gohan
H2O cluster total nodes:    1
H2O cluster free memory:    3.531 Gb
H2O cluster total cores:    4
H2O cluster allowed cores:  4
H2O cluster status:         accepting new members, healthy
H2O connection url:         http://localhost:54321
H2O connection proxy:
Python version:             2.7.12 final
--------------------------  ------------------------------

Parse progress: |█████████████████████████████████████████████████████████| 100%


In [11]:
train[3] = train[3].asfactor()

from h2o.estimators.deeplearning import H2ODeepLearningEstimator
model = H2ODeepLearningEstimator()
model.train(x=range(3), y=3, training_frame=train)

deeplearning Model Build progress: |██████████████████████████████████████| 100%


In [12]:
model.show()

Model Details
H2ODeepLearningEstimator :  Deep Learning
Model Key:  DeepLearning_model_python_1483860648623_1


ModelMetricsBinomial: deeplearning
** Reported on train data. **

MSE: 0.0238169429963
RMSE: 0.154327389003
LogLoss: 0.0985650502885
Mean Per-Class Error: 0.0733210047316
AUC: 0.976477631488
Gini: 0.952955262976
Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.216569993386: 


0     1    Error    Rate
-----  ----  ---  -------  --------------
0      9041  86   0.0094   (86.0/9127.0)
1      187   677  0.2164   (187.0/864.0)
Total  9228  763  0.0273   (273.0/9991.0)

Maximum Metrics: Maximum metrics at their respective thresholds



metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.21657      0.832207  229
max f2                       0.0502025    0.841287  315
max f0point5                 0.477478     0.895411  153
max accuracy                 0.299008     0.973276  200
max precision                0.999893     1         0
max recall                   1.87337e-05  1         399
max specificity              0.999893     1         0
max absolute_mcc             0.299008     0.820172  200
max min_per_class_accuracy   0.0144338    0.921296  357
max mean_per_class_accuracy  0.0214935    0.926679  346

Gains/Lift Table: Avg response rate:  8.65 %



group    cumulative_data_fraction    lower_threshold    lift       cumulative_lift    response_rate    cumulative_response_rate    capture_rate    cumulative_capture_rate    gain      cumulative_gain
--  -------  --------------------------  -----------------  ---------  -----------------  ---------------  --------------------------  --------------  -------------------------  --------  -----------------
    1        0.010009                    0.999628           11.5637    11.5637            1                1                           0.115741        0.115741                   1056.37   1056.37
    2        0.020018                    0.999006           11.5637    11.5637            1                1                           0.115741        0.231481                   1056.37   1056.37
    3        0.030027                    0.995667           11.5637    11.5637            1                1                           0.115741        0.347222                   1056.37   1056.37
    4        0.040036                    0.975242           11.3324    11.5058            0.98             0.995                       0.113426        0.460648                   1033.24   1050.58
    5        0.050045                    0.82876            11.2167    11.448             0.97             0.99                        0.112269        0.572917                   1021.67   1044.8
    6        0.10009                     0.0618243          5.7587     8.60336            0.498            0.744                       0.288194        0.861111                   475.87    760.336
    7        0.150035                    0.0143017          1.18186    6.13283            0.102204         0.530354                    0.0590278       0.920139                   18.1857   513.283
    8        0.20008                     0.00582592         0.624437   4.75504            0.054            0.411206                    0.03125         0.951389                   -37.5563  375.504
    9        0.30007                     0.00161626         0.185204   3.23227            0.016016         0.27952                     0.0185185       0.969907                   -81.4796  223.227
    10       0.40016                     0.000522166        0.173455   2.46718            0.015            0.213357                    0.0173611       0.987269                   -82.6545  146.718
    11       0.50035                     0.000182475        0.0693126  1.98703            0.00599401       0.171834                    0.00694444      0.994213                   -93.0687  98.7034
    12       0.600841                    8.15188e-05        0.0115176  1.65663            0.000996016      0.143262                    0.00115741      0.99537                    -98.8482  65.6629
    13       0.70003                     4.14858e-05        0.0116687  1.42355            0.00100908       0.123106                    0.00115741      0.996528                   -98.8331  42.355
    14       0.80002                     1.9221e-05         0.0347257  1.24997            0.003003         0.108095                    0.00347222      1                          -96.5274  24.9969
    15       0.90001                     6.98894e-06        0          1.1111             0                0.0960854                   0               1                          -100      11.1099
    16       1                           1.53955e-23        0          1                  0                0.0864778                   0               1                          -100      0


Scoring History: 


timestamp            duration          training_speed    epochs     iterations    samples      training_rmse    training_logloss    training_auc    training_lift    training_classification_error
--  -------------------  ----------------  ----------------  ---------  ------------  -----------  ---------------  ------------------  --------------  ---------------  -------------------------------
    2017-01-08 13:05:06  0.000 sec                           0          0             0            nan              nan                 nan             nan              nan
    2017-01-08 13:05:25  20.159 sec        5323 obs/sec      0.0156016  1             100069       0.199517         0.305035            0.944395        11.5637          0.0307277
    2017-01-08 13:05:39  34.334 sec        6122 obs/sec      0.0312408  2             200379       0.194225         0.169247            0.960826        11.5637          0.0305275
    2017-01-08 13:05:51  46.247 sec        6780 obs/sec      0.0468788  3             300681       0.168234         0.111309            0.972669        11.5637          0.0305275
    2017-01-08 13:06:00  54.880 sec        7600 obs/sec      0.0625018  4             400887       0.206982         0.329509            0.945921        11.5637          0.0328295
    2017-01-08 13:06:09  1 min  3.376 sec  8221 obs/sec      0.0781933  5             501533       0.175628         0.142236            0.976277        11.5637          0.0285257
    2017-01-08 13:06:16  1 min 10.841 sec  8817 obs/sec      0.0938438  6             601915       0.167547         0.137604            0.974956        11.5637          0.0283255
    2017-01-08 13:06:23  1 min 17.485 sec  9388 obs/sec      0.10937    7             701503       0.198283         0.142385            0.972114        11.5637          0.0291262
    2017-01-08 13:06:29  1 min 23.864 sec  9909 obs/sec      0.124938   8             801352       0.166702         0.110256            0.977357        11.5637          0.027725
    2017-01-08 13:06:36  1 min 30.510 sec  10326 obs/sec     0.140538   9             901415       0.226825         0.397621            0.951822        11.5637          0.0272245
    2017-01-08 13:06:42  1 min 37.128 sec  10686 obs/sec     0.156138   10            1.00147e+06  0.166271         0.116739            0.976751        11.5637          0.0265239
    2017-01-08 13:06:49  1 min 43.674 sec  11009 obs/sec     0.171763   11            1.10169e+06  0.223605         0.338049            0.957106        11.5637          0.0312281
    2017-01-08 13:06:55  1 min 49.817 sec  11329 obs/sec     0.187275   12            1.20119e+06  0.161658         0.160179            0.960879        11.5637          0.0294265
    2017-01-08 13:07:01  1 min 56.239 sec  11587 obs/sec     0.202819   13            1.30088e+06  0.154327         0.0985651           0.976478        11.5637          0.0273246

In [42]:
## Read the test files
ip_files = []
test_files = os.listdir('E:\\SigTuple_Hack\\Train_Data\\')
ip_files += [f for f in test_files if f.endswith('.jpg') and 'mask' not in f]

ip_files

['017532875DDF.jpg',
 '1467973104.jpg',
 '1467973122.jpg',
 '1467973178.jpg',
 '54A84627F362.jpg',
 'train-0.jpg',
 'train-1.jpg',
 'train-10.jpg',
 'train-100.jpg',
 'train-101.jpg',
 'train-102.jpg',
 'train-103.jpg',
 'train-104.jpg',
 'train-105.jpg',
 'train-106.jpg',
 'train-107.jpg',
 'train-108.jpg',
 'train-109.jpg',
 'train-11.jpg',
 'train-110.jpg',
 'train-111.jpg',
 'train-112.jpg',
 'train-113.jpg',
 'train-114.jpg',
 'train-115.jpg',
 'train-116.jpg',
 'train-117.jpg',
 'train-118.jpg',
 'train-119.jpg',
 'train-12.jpg',
 'train-120.jpg',
 'train-121.jpg',
 'train-122.jpg',
 'train-123.jpg',
 'train-124.jpg',
 'train-125.jpg',
 'train-126.jpg',
 'train-127.jpg',
 'train-128.jpg',
 'train-129.jpg',
 'train-13.jpg',
 'train-130.jpg',
 'train-131.jpg',
 'train-132.jpg',
 'train-133.jpg',
 'train-134.jpg',
 'train-135.jpg',
 'train-136.jpg',
 'train-137.jpg',
 'train-138.jpg',
 'train-139.jpg',
 'train-14.jpg',
 'train-140.jpg',
 'train-141.jpg',
 'train-142.jpg',
 'train-14

In [43]:
#valList = ['54A84627F362.jpg', '1467973178.jpg', '017532875DDF.jpg', '1467973122.jpg']
grid = joblib.load('E:\\SigTuple_Hack\\Models\\grid_linearSVC_v0.pkl')

for img_file in ip_files:
    input_file = 'E:\\SigTuple_Hack\\Train_Data\\' + img_file
    mask_file = 'E:\\SigTuple_Hack\\Train_Data\\' + img_file[:-4] + '-mask.jpg'
    mask_file2 = 'E:\\SigTuple_Hack\\Train_Data\\' + img_file[:-4] + '-mask2.jpg'
    
    print input_file
    
    # Load the image & flatten 3d to 2d .
    imgcolor = imread(input_file)/255.0
    imgshape = imgcolor.shape
    imgdf = pd.DataFrame(imgcolor.transpose(2,0,1).reshape(3,-1).transpose(1,0))
    imgdf.columns = ['Red', 'Green', 'Blue']
    #imgdf.drop('Unnamed: 0', 1, inplace = True)
    test = h2o.H2OFrame(imgdf)
    
    # Create mask, using LinearSVC model
    Pred = model.predict(test)['predict']
    print Pred.columns
    print Pred.shape
    print imgdf.shape
    imgdf.loc[:,'Predict'] = tmp['predict']. as_data_frame()
    
    imgmask = imread(mask_file)/255.0
    maskShape = imgmask.shape
    imgdf['Mask'] = imgmask.reshape(maskShape[0]*maskShape[1])
    
    # Update the mask column
    imgdf.Mask[dfTrain.Mask < 0.1] = 0
    imgdf.Mask[dfTrain.Mask > 0.9] = 1

    # Calculate vanity figures
    print sklearn.metrics.accuracy_score(imgdf.Mask, imgdf.Predict)
    print sklearn.metrics.f1_score(imgdf.Mask, imgdf.Predict)
    print sklearn.metrics.jaccard_similarity_score(imgdf.Mask, imgdf.Predict)
    print sklearn.metrics.confusion_matrix(imgdf.Mask, imgdf.Predict)
    
    
    
    # Save mask in directory
    imgmask2= imgdf['Predict'].reshape(maskShape[0], maskShape[1])
    imsave(mask_file2, imgmask2)
    
    
    

E:\SigTuple_Hack\Train_Data\017532875DDF.jpg
Parse progress: |█████████████████████████████████████████████████████████| 100%
deeplearning prediction progress: |███████████████████████████████████████| 100%
['predict']
(752874, 1)
(752874, 3)


D:\Anaconda2\lib\site-packages\ipykernel\__main__.py:31: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda2\lib\site-packages\ipykernel\__main__.py:32: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


0.98082414853
0.0285310544378
0.98082414853
[[738225   7545]
 [  6892    212]]
E:\SigTuple_Hack\Train_Data\1467973104.jpg
Parse progress: |█████████████████████████████████████████████████████████| 100%
deeplearning prediction progress: |███████████████████████████████████████| 100%
['predict']
(125904, 1)
(125904, 3)
0.987712860592
0.0
0.987712860592
[[124357    363]
 [  1184      0]]
E:\SigTuple_Hack\Train_Data\1467973122.jpg
Parse progress: |█████████████████████████████████████████████████████████| 100%
deeplearning prediction progress: |███████████████████████████████████████| 100%
['predict']
(629090, 1)
(629090, 3)
0.978502281073
0.0303986234586
0.978502281073
[[615354   6760]
 [  6764    212]]
E:\SigTuple_Hack\Train_Data\1467973178.jpg
Parse progress: |█████████████████████████████████████████████████████████| 100%
deeplearning prediction progress: |███████████████████████████████████████| 100%
['predict']
(1074336, 1)
(1074336, 3)
0.976440331516
0.017086715079
0.976440331516
[

D:\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true samples.
  'recall', 'true', average, warn_for)


0.0
0.999938964844
[[16383     1]
 [    0     0]]
E:\SigTuple_Hack\Train_Data\train-1.jpg
Parse progress: |█████████████████████████████████████████████████████████| 100%
deeplearning prediction progress: |███████████████████████████████████████| 100%
['predict']
(16384, 1)
(16384, 3)
0.999938964844
0.0
0.999938964844
[[16383     1]
 [    0     0]]
E:\SigTuple_Hack\Train_Data\train-10.jpg
Parse progress: |█████████████████████████████████████████████████████████| 100%
deeplearning prediction progress: |███████████████████████████████████████| 100%
['predict']
(16384, 1)
(16384, 3)
0.999938964844
0.0
0.999938964844
[[16383     1]
 [    0     0]]
E:\SigTuple_Hack\Train_Data\train-100.jpg
Parse progress: |█████████████████████████████████████████████████████████| 100%
deeplearning prediction progress: |███████████████████████████████████████| 100%
['predict']
(16384, 1)
(16384, 3)
0.999938964844
0.0
0.999938964844
[[16383     1]
 [    0     0]]
E:\SigTuple_Hack\Train_Data\train-101.jpg
Pa

In [24]:
tmp.columns

[u'predict', u'p0', u'p1']

In [25]:
tmp.shape

(1144832, 3)

In [26]:
imgdf.shape

(1144832, 3)

In [30]:
 tmp['predict'].mean()

[0.011689924809928443]

In [34]:
imgdf.loc[:,'Predict'] = tmp['predict']. as_data_frame()

In [36]:
imgdf.head()

Red     Green      Blue  Predict
0  0.894118  0.901961  0.819608        0
1  0.894118  0.905882  0.823529        0
2  0.894118  0.905882  0.823529        0
3  0.894118  0.913725  0.835294        0
4  0.890196  0.909804  0.831373        0