In [4]:
import pandas as pd
import numpy as np
np.random.seed(1337)  # for reproducibility

from sklearn import svm
from sklearn.externals import joblib
from sklearn.cross_validation import train_test_split
from sklearn.model_selection import GridSearchCV




In [2]:
dfTrain = pd.read_csv('Train.csv')
dfTrain.shape

train, test = train_test_split(dfTrain, test_size = 0.5)
#validate, test = train_test_split(test, test_size = 0.5)

print train.shape
#print validate.shape
print test.shape

(3207006, 5)
(3207006, 5)


In [3]:
from sklearn import svm

lin_clf = svm.LinearSVC()

X = dfTrain[['Red', 'Green', 'Blue']]
y = dfTrain.Mask

In [4]:
## Train: 50 validate:50 test: 50 >>> 0.69 >>> linearSVC_v1.pkl
## Train: with all data >>>    >>> linearSVC_v2.pkl
lin_clf.fit(X, y, verbose = 1)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [5]:
from sklearn.externals import joblib
joblib.dump(lin_clf, 'linearSVC_v2.pkl') 

['linearSVC_v2.pkl',
 'linearSVC_v2.pkl_01.npy',
 'linearSVC_v2.pkl_02.npy',
 'linearSVC_v2.pkl_03.npy']

In [6]:
lin_clf_v0 = joblib.load('linearSVC_v1.pkl')

In [16]:
train['PredMask0'] = lin_clf_v0.predict(train[['Red', 'Green', 'Blue']])
test['PredMask0'] = lin_clf_v0.predict(test[['Red', 'Green', 'Blue']])
dfTrain['PredMask0'] = lin_clf_v0.predict(dfTrain[['Red', 'Green', 'Blue']])

train['PredMask1'] = lin_clf.predict(train[['Red', 'Green', 'Blue']])
test['PredMask1'] = lin_clf.predict(test[['Red', 'Green', 'Blue']])
dfTrain['PredMask1'] = lin_clf.predict(dfTrain[['Red', 'Green', 'Blue']])

D:\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
D:\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
D:\Anaconda2\lib\site-packages\ipykernel\__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-d

In [19]:
test.columns 

Index([u'Unnamed: 0', u'Red', u'Green', u'Blue', u'Mask', u'PredMask0',
       u'PredMask1'],
      dtype='object')

In [20]:
import sklearn.metrics 
print "Train ~ Lin_clf v0"
print sklearn.metrics.accuracy_score(train.Mask,train.PredMask0)
print sklearn.metrics.f1_score(train.Mask,train.PredMask0)

print "Test ~ Lin_clf v0"
print sklearn.metrics.accuracy_score(test.Mask,test.PredMask0)
print sklearn.metrics.f1_score(test.Mask,test.PredMask0)

Train ~ Lin_clf v0
0.970030926041
0.796453055078
Test ~ Lin_clf v0
0.970090171331
0.797421758349


In [15]:
train.columns

Index([u'Unnamed: 0', u'Red', u'Green', u'Blue', u'Mask', u'PredMask0'], dtype='object')

In [21]:
print "Train ~ Lin_clf v1"
print sklearn.metrics.accuracy_score(train.Mask,train.PredMask1)
print sklearn.metrics.f1_score(train.Mask,train.PredMask1)

print "Test ~ Lin_clf v1"
print sklearn.metrics.accuracy_score(test.Mask,test.PredMask1)
print sklearn.metrics.f1_score(test.Mask,test.PredMask1)

Train ~ Lin_clf v1
0.969986336165
0.7959120497
Test ~ Lin_clf v1
0.970044646003
0.796900667012


In [22]:
print "dfTrain ~ Lin_clf v0"
print sklearn.metrics.accuracy_score(dfTrain.Mask,dfTrain.PredMask0)
print sklearn.metrics.f1_score(dfTrain.Mask,dfTrain.PredMask0)

print "dfTrain ~ Lin_clf v1"
print sklearn.metrics.accuracy_score(dfTrain.Mask,dfTrain.PredMask1)
print sklearn.metrics.f1_score(dfTrain.Mask,dfTrain.PredMask1)

dfTrain ~ Lin_clf v0
0.970060548686
0.79693808278
dfTrain ~ Lin_clf v1
0.970015491084
0.796407077866


In [9]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(svm.LinearSVC(), param_grid={'C': [1, 10]}, scoring='f1', verbose=4)

In [10]:
X = train[['Red', 'Green', 'Blue']]
y = train.Mask

In [11]:
grid.fit(X, y)

Fitting 3 folds for each of 2 candidates, totalling 6 fits
[CV] C=1 .............................................................
[CV] .............................. C=1, score=0.797037, total= 1.4min
[CV] C=1 .............................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.5min remaining:    0.0s


[CV] .............................. C=1, score=0.796083, total= 1.5min
[CV] C=1 .............................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  3.0min remaining:    0.0s


[CV] .............................. C=1, score=0.796026, total= 1.5min
[CV] C=10 ............................................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:  4.5min remaining:    0.0s


[CV] ............................. C=10, score=0.797079, total= 3.9min
[CV] C=10 ............................................................
[CV] ............................. C=10, score=0.796160, total= 4.1min
[CV] C=10 ............................................................
[CV] ............................. C=10, score=0.796096, total= 3.8min


[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed: 16.2min finished


GridSearchCV(cv=None, error_score='raise',
       estimator=LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0),
       fit_params={}, iid=True, n_jobs=1, param_grid={'C': [1, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='f1', verbose=4)

In [12]:
train['PredMask'] = grid.predict(train[['Red', 'Green', 'Blue']])
test['PredMask'] = grid.predict(test[['Red', 'Green', 'Blue']])


D:\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
D:\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [14]:
import sklearn.metrics 
print "Train ~ Grid_LinSVC v1"
print sklearn.metrics.accuracy_score(train.Mask,train.PredMask)
print sklearn.metrics.f1_score(train.Mask,train.PredMask)

print "Test ~  Grid_LinSVC v1"
print sklearn.metrics.accuracy_score(test.Mask,test.PredMask)
print sklearn.metrics.f1_score(test.Mask,test.PredMask)

Train ~ Grid_LinSVC v1
0.970031861493
0.796441733384
Test ~  Grid_LinSVC v1
0.970091730418
0.79741734359


In [15]:
joblib.dump(grid, 'grid_linearSVC_v0.pkl')

['grid_linearSVC_v0.pkl']

In [30]:
############################################################################
## The following can be used as a validation check
##
############################################################################


import sklearn.metrics
from scipy.misc import imread, imsave
from sklearn.externals import joblib

valList = ['54A84627F362.jpg', '1467973178.jpg', '017532875DDF.jpg', '1467973122.jpg']
grid = joblib.load('E:\\SigTuple_Hack\\Models\\grid_linearSVC_v0.pkl')

for img_file in valList:
    input_file = 'E:\\SigTuple_Hack\\Train_Data\\' + img_file
    mask_file = 'E:\\SigTuple_Hack\\Train_Data\\' + img_file[:-4] + '-mask.jpg'
    mask_file2 = 'E:\\SigTuple_Hack\\Train_Data\\' + img_file[:-4] + '-mask2.jpg'
    
    print input_file
    
    # Load the image & flatten 3d to 2d .
    imgcolor = imread(input_file)/255.0
    imgshape = imgcolor.shape
    imgdf = pd.DataFrame(imgcolor.transpose(2,0,1).reshape(3,-1).transpose(1,0))
    imgdf.columns = ['Red', 'Green', 'Blue']
    
    # Create mask, using LinearSVC model
    imgdf['PredMask'] = grid.predict(imgdf)
    
    imgmask = imread(mask_file)/255.0
    maskShape = imgmask.shape
    imgdf['Mask'] = imgmask.reshape(maskShape[0]*maskShape[1])
    
    # Update the mask column
    imgdf.Mask[dfTrain.Mask < 0.1] = 0
    imgdf.Mask[dfTrain.Mask > 0.9] = 1

    # Calculate vanity figures
    print sklearn.metrics.accuracy_score(imgdf.Mask, imgdf.PredMask)
    print sklearn.metrics.f1_score(imgdf.Mask, imgdf.PredMask)
    print sklearn.metrics.jaccard_similarity_score(imgdf.Mask, imgdf.PredMask)
    print sklearn.metrics.confusion_matrix(imgdf.Mask, imgdf.PredMask)
    
    
    
    # Save mask in directory
    imgmask2= imgdf['PredMask'].reshape(maskShape[0], maskShape[1])
    imsave(mask_file2, imgmask2)
    
    
    
    

E:\SigTuple_Hack\Train_Data\54A84627F362.jpg
0.977353882491
0.0166135639508
0.977353882491
[[1118687   13073]
 [  12853     219]]
E:\SigTuple_Hack\Train_Data\1467973178.jpg
0.980498652191
0.00276072159551
0.980498652191
[[1053356    7908]
 [  13043      29]]
E:\SigTuple_Hack\Train_Data\017532875DDF.jpg
0.996148093838
0.756752222781
0.996148093838
[[745463    307]
 [  2593   4511]]
E:\SigTuple_Hack\Train_Data\1467973122.jpg
0.981932632851
0.0114802574361
0.981932632851
[[617658   4456]
 [  6910     66]]
